spring.application.name=DevPulse

server.port=8080
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.maximum-pool-size=5
jwt.secret=bXlzdXBlcnNlY3JldGtleXRoYXRpc2F0bGVhc3QyNTZiaXRzbG9uZzEyMzQ1Njc4
jwt.expiration=86400000
